services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Rsaauth\:
    resource: '../Classes/*'

  TYPO3\CMS\Rsaauth\EventHandler\ModifyPageLayoutOnLoginProviderSelection:
      tags:
        - name: event.listener
          method: 'enableRsaEncryption'
          event: TYPO3\CMS\Backend\LoginProvider\Event\ModifyPageLayoutOnLoginProviderSelectionEvent
